server:
  port: 1004

zuul:
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      url: http://localhost:1002/multiplications
    results:
      path: /results/**
      url: http://localhost:1002/results
    leaders:
      path: /leaders/**
      url: http://localhost:1003/leaders
    stats:
      path: /stats/**
      url: http://localhost:1003/stats

endpoints:
  trace:
    sensitive: false

ribbon:
  eureka:
    enabled: false